### ISSUE TITLE
Nothing reported

### ISSUE THREAD

**Issue by Firesphere** [phptek/silverstripe-sentry#55]
I have my yml set up on a Silverstripe 3 website like so:
```
phptek\Sentry\Adaptor\SentryClientAdaptor:
  opts:
    # Example DSN only. Obviously you'll need to setup your own Sentry "Project"
    dsn: https://dsn-domain@here.io
PhpTek\Sentry\Handler\SentryHandler:
  # One of the permitted severities: DEBUG|INFO|WARNING|ERROR|FATAL
  log_level: WARNING
```

However, it does not seem to report anything. Did I miss a step?
